import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs';
import { neon } from '@neondatabase/serverless';

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getData() {
  const sql = neon(process.env.DATABASE_URL);
  const response = await sql`SELECT version()`;
  console.log(response);
  return response;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = getData();
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
